@startuml er-diagram

' https://raw.githubusercontent.com/GC211MP/API/main/documents/erd.puml

left to right direction

title

=[Server] Entity Relationship Diagram

end title

map lecture {
    <color:red>**(PK)**</color> idx => int
    lecname => varchar
    lecnum => varchar
    profname => varchar
}

map lec_time {
    <color:red>**(PK)**</color> idx => int
    name => int
    dotw => int
    start => timestamp
    end => timestamp
}

map lec_room {
    <color:red>**(PK)**</color> idx => int
    building => varchar
    classroom => varchar
}

map lec_time_link {
    <color:blue>**(FK)**</color> lecture_idx => int
    <color:blue>**(FK)**</color> lec_time_idx => int
}

map lec_room_link {
    <color:blue>**(FK)**</color> lecture_idx => int
    <color:blue>**(FK)**</color> lec_room_idx => int
}

map reservation {
    <color:red>**(PK)**</color> idx => int
    userid => varchar
    start => timestamp
    end => timestamp
    <color:blue>**(FK)**</color> lec_room_idx => int
    enable => int
    fb_key => varchar
}


' lec_time
' lecture
' lec_room
' lec_time_link
' lec_room_link
' reservation

lec_time_link }o.down.|| lecture
lec_time_link }o.down.|| lec_time

lec_room_link }o.up.|| lecture
lec_room_link }o.up.|| lec_room

reservation }o..|| lec_room

@enduml
